name: Coding Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Perform coding style verification
        run: |
          cargo fmt -- --check
